config:
  use_colors: false

realweb: # название профиля, которое указали в dbt_project.yml
  target: dev
  outputs:
    
    dev:
      type: bigquery
      method: service-account
      project: realweb-152714 # название проекта в BigQuery
      dataset: "{{ env_var('DEV_DATASET') }}" # название вашего личного датасета (если его нет, он будет создан)
      threads: 4
      keyfile: "{{ env_var('PATH_TO_KEYFILE') }}"
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1
    
    prod:
      type: bigquery
      method: service-account
      project: realweb-152714 # название проекта в BigQuery
      dataset: dbt_production # название датасета для продакшн среды
      threads: 4
      keyfile: "{{ env_var('PATH_TO_KEYFILE') }}"
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1