# это не тот profiles.yml, который вы ищете (с)
# нужную вам конфигурацию для profiles.yml в .dbt можно найти в файле README
# этот файл используется для продакшена в GCP
config:
  use_colors: false

realweb: # название профиля, которое указали в dbt_project.yml
  target: dev
  outputs:
    
    dev:
      type: bigquery
      method: service-account
      project: realweb-152714 # название проекта в BigQuery
      dataset: "{{ env_var('DEV_DATASET') }}"
      threads: 4
      keyfile: "{{ env_var('PATH_TO_KEYFILE') }}"
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1
    
    prod:
      type: bigquery
      method: service-account
      project: realweb-152714 # название проекта в BigQuery
      dataset: dbt_production # название датасета для продакшн среды
      threads: 4
      keyfile: "{{ env_var('PATH_TO_KEYFILE') }}"
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1