version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_af_installs
    description: "установки приложения"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      
      - name: appsflyer_id
        description: "id установки"
        tests:
          - unique
          - not_null

#Ваш заказчик требователен.
# В дашборде не должно быть случайно попавших туда NULL-компаний,
#а в столбце "платформа" не должно быть ничего кроме "ios" и "android".

#В файле schema.yml задайте для вашей модели username_af_installs два теста:
#  один для названия кампании,
#  а другой для платформы (вдохновиться примерами можно в этом же файле).

  - name: schobanu_af_installs
    description: "schobanu установки приложения"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      - name: campaign_name
        description: "кампания"
        tests:
          - not_null

- name: dshatalov_af_installs
    description: "check_campaign_name"
    columns:
      - name: campaign_name
        description: "название компании"
        tests:
          - not_null
      
      - name: platform
        description: "check_platform"
        tests:
          - accepted_values:
              values: ['ios', 'android']