version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_af_installs
    description: "установки приложения"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      
      - name: appsflyer_id
        description: "id установки"
        tests:
          - unique
          - not_null
  - name: dbt_adurakhov_af_installs
    description: "установки приложения"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      
      - name: campaign_name
        description: "название кампании"
        tests:
          - not_null

#Ваш заказчик требователен.
# В дашборде не должно быть случайно попавших туда NULL-компаний,
#а в столбце "платформа" не должно быть ничего кроме "ios" и "android".

#В файле schema.yml задайте для вашей модели username_af_installs два теста:
#  один для названия кампании,
#  а другой для платформы (вдохновиться примерами можно в этом же файле).


  - name: schobanu_af_installs 
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      - name: campaign_name
        description: "кампания"
        tests: 
          - not_null

  - name: pmoiseev_af_installs
    description: "pmoiseev установки приложения"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      - name: campaign_name
        description: "кампания"
        tests: 
          - not_null

  - name: klarchenko_af_installs
    description: "Названия компаний и платформы установки приложений"
    columns:
      - name: campaign_name
        description: "название компании"
        tests:
          - not_null
      
      - name: platform
        description: "платформа установки приложения"
        tests:
          - accepted_values:
              values: ['ios', 'android']

  - name: krepin_af_installs
    description: "krepin установки приложения"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      - name: campaign_name
        description: "кампания"
        tests:
          - not_null   

  - name: etaranova_af_installs
    columns: 
      - name: campaign_name
        tests:
          - not_null

      - name: platform
        tests:
          - accepted_values:
              values:
                - ios
                - android

  - name: nkovaleva_af_installs
    description: "установки, клики, показы и расходы по всем известным источникам"      
    columns:
      - name: campaign_name
        description: "название рекламной кампании"
        tests:
          - not_null
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']


  - name: dsimonova_af_installs
    description: "dsimonova установки приложения"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      - name: campaign_name
        description: "кампания"
        tests:
          - not_null
          
  - name: aakhtyamova_af_installs
    description: "aakhtyamova установки приложения"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      - name: campaign_name
        description: "кампания"
        tests:
          - not_null  


  - name: dshatalov_af_instals

    description: "check_campaign_name"
    columns:
      - name: campaign_name
        description: "название компании"
        tests:
          - not_null
      
      - name: platform
        description: "check_platform"
        tests:
          - accepted_values:
              values: ['ios', 'android']

  - name: srybalko_af_installs
    description: "schobanu установки приложения"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      
      - name: campaign_name
        description: "название кампании"
        tests:
          - not_null  

  - name: agasanov_af_installs
    description: "agasanov установки приложения"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      - name: campaign_name
        description: "кампания"
        tests: 
          - not_null 


  - name: omaltseva_af_installs
    columns:
      - name: platform
        tests:
          - accepted_values:
              values: ['ios', 'android']
      - name: campaign_name
        description: "название кампании"
        tests:
          - not_null

  - name: szhankov_af_installs
    description: "данные из рекламных кабинетов + установки"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']

      - name: campaign_name
        description: "название кампании"
        tests:
          - not_null

  - name: kshulakov_af_installs
    description: "kshulakov установки приложения"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      - name: campaign_name
        description: "кампания"
        tests: 
          - not_null 
          
  - name: aiatcyna_af_installs
    description: "aiatcyna installs clicks costs impressions for all sources"
    columns:
      - name: platform
        description: "intstall platform"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      - name: campaign_name
        description: campaign
        tests: 
          - not_null


  - name: sokruzhnov_af_installs
    description: "sokruzhnov установки приложения"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      - name: campaign_name
        description: "кампания"
        tests: 
          - not_null 
          
  - name: kportnova_af_installs
    columns:
      - name: platform
        tests:
          - accepted_values:
              values: ['ios', 'android']
      - name: campaign_name
        tests:
          - not_null
                   
  - name: dgamayunov_af_installs
    description: "Проверка ненулевых названий кампаний и платформы"
    columns:
      - name: campaign_name
        description: "Название кампании"
        tests:
          - not_null

      - name: platform
        description: "Проверка ios и android"
        tests:
          - accepted_values:
              values: ['ios', 'android']

      - name: costs
        description: "Тест на превышение лимита по величине расходов (условно не больше 5000)"
        tests:
          - exceed_costs_limit

  - name: vglukhovtsev_af_installs
    description: "данные из installs и рекламных кабинетов"
    columns:
      - name: platform
        description: "intstall platform"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      - name: campaign_name
        description: campaign
        tests: 
          - not_null 


  - name: anasonova_af_installs
    description: "установки приложения"
    columns:
      - name: platform
        description: "платформа установки"
        tests:
          - accepted_values:
              values: ['ios', 'android']
      - name: campaign_name
        description: "кампания"
        tests: 
          - not_null 

  - name: dzhdanov_af_installs
    description: "установки приложения по источникам"      
    columns:
      - name: campaign_name
        description: "рекламная кампания"
        tests:
          - not_null
      - name: platform
        description: "платформа приложения"
        tests:
          - accepted_values:
              values: ['ios', 'android']
              

